apiVersion: apps/v1
kind: Deployment
metadata:
  name: azurite
  labels:
    app: azurite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azurite
  template:
    metadata:
      labels:
        app: azurite
    spec:
      containers:
        - name: azurite
          image: mcr.microsoft.com/azure-storage/azurite
          ports:
            - containerPort: 10000
            - containerPort: 10001
            - containerPort: 10002
          args: ["azurite", "-l", "/data", "--blobHost", "0.0.0.0", "--queueHost", "0.0.0.0", "--tableHost", "0.0.0.0"]
          volumeMounts:
            - name: azurite-storage
              mountPath: /data
      volumes:
        - name: azurite-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: azurite
spec:
  selector:
    app: azurite
  ports:
    - protocol: TCP
      name: blob
      port: 10000
      targetPort: 10000
    - protocol: TCP
      name: queue
      port: 10001
      targetPort: 10001
    - protocol: TCP
      name: table
      port: 10002
      targetPort: 10002
