apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: europe-central2-docker.pkg.dev/gd-gcp-internship-cd/streamphony-repo/frontend
          ports:
            - containerPort: 5173
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "5173"
            - name: REACT_APP_API_URL
              value: "http://34.116.230.17"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5173
      nodePort: 30080
